### ISSUE TITLE
External patch support

### ISSUE THREAD

**Issue by GauthierPLM** [somasis/lux#2]
Hi,

It would be nice if Lux was able to handle external patch and automaticallly apply to kernel' sources before compiling them.
I'm thinking to patch to reduce kernel log-level for example.

**Comment by somasis** [comment]
Sorry for not replying sooner, got busy with schoolwork and overlooked this in my notifications.

I'd say that external patching is out of scope for the most part. In fact, patching is the one of the reasons I allow for overriding functions with lux.conf.

In my `lux.conf`, I have a redefinition of kernel_patch that is something like this... (don't have the exact definition as I'm away from my Linux machine right now)

```bash
kernel_patch() {
    default_kernel_patch
    curl -#L "https://raw.githubusercontent.com/graysky2/kernel_gcc_patch/master/enable_additional_cpu_optimizations_for_gcc_v4.9%2B_kernel_v3.15%2B.patch" | patch -p1
}
```
